In [1]:
import pandas as pd
import requests
import time
from bs4 import BeautifulSoup
from io import StringIO

In [2]:
# years we are scraping from
years = list(range(1989, 2025))

# webscraping url
url = f"https://www.basketball-reference.com/awards/awards_YEAR.html"

In [6]:
# saving html data to mvps folder to be used later
for year in years:
    url = f"https://www.basketball-reference.com/awards/awards_{year}.html"
    data = requests.get(url)
    with open("mvps/{}.html".format(year), "w+", encoding="utf-8") as file:
        file.write(data.text)
    # basketballreference hates me so i am sleeping so i dont get banned again
    time.sleep(10)

In [7]:
# taking our scraped files and getting only the mvp charts
mvpdfs = []
for year in years:
    with open("mvps/{}.html".format(year), encoding="utf-8") as file:
        page = file.read()
    soup = BeautifulSoup(page, "html.parser")
    # useless header at the top of the chart
    soup.find("tr", class_="over_header").decompose()
    mvp_chart = soup.find(id="mvp")
    df = pd.read_html(StringIO(str(mvp_chart)))[0]
    df["Year"] = year
    mvpdfs.append(df)
mvps = pd.concat(mvpdfs)
mvps.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Magic Johnson,29,LAL,42.5,664.5,850,0.782,77,37.5,...,7.9,12.8,1.8,0.3,0.509,0.314,0.911,16.1,0.267,1989
1,2,Michael Jordan,25,CHI,27.5,598.8,850,0.704,81,40.2,...,8.0,8.0,2.9,0.8,0.538,0.276,0.850,19.8,0.292,1989
2,3,Karl Malone,25,UTA,5.0,362.0,850,0.426,80,39.1,...,10.7,2.7,1.8,0.9,0.519,0.313,0.766,15.2,0.233,1989
3,4,Patrick Ewing,26,NYK,8.0,200.0,850,0.235,80,36.2,...,9.3,2.4,1.5,3.5,0.567,0.000,0.746,10.9,0.181,1989
4,5,Hakeem Olajuwon,26,HOU,2.0,179.3,850,0.211,82,36.9,...,13.5,1.8,2.6,3.4,0.508,0.000,0.696,12.4,0.197,1989

In [4]:
mvps.tail()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
4,5,Jalen Brunson,27,NYK,0.0,142.0,990,0.143,77,35.4,...,3.6,6.7,0.9,0.2,0.479,0.401,0.847,11.2,0.198,2024
5,6,Jayson Tatum,25,BOS,0.0,86.0,990,0.087,74,35.7,...,8.1,4.9,1.0,0.6,0.471,0.376,0.833,10.4,0.189,2024
6,7,Anthony Edwards,22,MIN,0.0,18.0,990,0.018,79,35.1,...,5.4,5.1,1.3,0.5,0.461,0.357,0.836,7.5,0.130,2024
7,8,Domantas Sabonis,27,SAC,0.0,3.0,990,0.003,82,35.7,...,13.7,8.2,0.9,0.6,0.594,0.379,0.704,12.6,0.206,2024
8,9,Kevin Durant,35,PHO,0.0,1.0,990,0.001,75,37.2,...,6.6,5.0,0.9,1.2,0.523,0.413,0.856,8.3,0.142,2024

In [11]:
# weird stuff i can just spot replace so no issues happen later
mvps = mvps.replace("Luka DonÄiÄ", "Luka Dončić")
mvps = mvps.replace("Nikola JokiÄ", "Nikola Jokić")
mvps = mvps.replace("Goran DragiÄ", "Goran Dragić")
mvps = mvps.replace("Peja StojakoviÄ", "Peja Stojaković")
mvps = mvps.replace("Manu GinÃ³bili", "Manu Ginóbili")

In [12]:
mvps.to_csv("mvpsfix.csv")